/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mycompany.mavenproject1.LineSegment;
import com.mycompany.mavenproject1.DrawingPanel;
import com.mycompany.mavenproject1.Node;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class LineSegmentInfo extends javax.swing.JFrame implements Node {
Node parent;
    int i_l ;
    private DrawingPanel d;
    JComboBox c = new JComboBox<>();
    Color color;
    /**
     * Creates new form LineSegmentInfo
     */
    
    public LineSegmentInfo(DrawingPanel d, JComboBox c,int i_l) {
        initComponents();
        this.d = d;
        this.c = c;
        this.i_l = i_l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        xaxisLabel = new javax.swing.JLabel();
        xaxisTextField = new javax.swing.JTextField();
        yaxisLabel = new javax.swing.JLabel();
        yaxisTextField = new javax.swing.JTextField();
        endPointLabel = new javax.swing.JLabel();
        lineColorButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        xaxisOfEnfPointLabel = new javax.swing.JLabel();
        xaxisOfEndPointTextField = new javax.swing.JTextField();
        yaxisOfEndPointLabel = new javax.swing.JLabel();
        yaxisOfEndPointTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Line Segment");

        positionLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        positionLabel.setText("Postion:");

        xaxisLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisLabel.setText("X1:");

        xaxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisTextFieldActionPerformed(evt);
            }
        });

        yaxisLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisLabel.setText("Y1:");

        yaxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisTextFieldActionPerformed(evt);
            }
        });

        endPointLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        endPointLabel.setText("Dimensions of the end-point:");

        lineColorButton.setBackground(new java.awt.Color(0, 0, 0));
        lineColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        lineColorButton.setForeground(new java.awt.Color(255, 255, 255));
        lineColorButton.setText("Select Color");
        lineColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineColorButtonActionPerformed(evt);
            }
        });

        setButton.setBackground(new java.awt.Color(0, 0, 0));
        setButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        setButton.setForeground(new java.awt.Color(255, 255, 255));
        setButton.setText("Create Line");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        xaxisOfEnfPointLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisOfEnfPointLabel.setText("X2:");

        xaxisOfEndPointTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisOfEndPointTextFieldActionPerformed(evt);
            }
        });

        yaxisOfEndPointLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisOfEndPointLabel.setText("Y2:");

        yaxisOfEndPointTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisOfEndPointTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endPointLabel)
                    .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineColorButton))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yaxisOfEndPointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(147, 147, 147)))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(yaxisOfEndPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(yaxisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xaxisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(xaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addComponent(yaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(xaxisOfEnfPointLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(xaxisOfEndPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(positionLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xaxisLabel)
                            .addComponent(xaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yaxisLabel)
                            .addComponent(yaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(endPointLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xaxisOfEnfPointLabel)
                        .addComponent(xaxisOfEndPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaxisOfEndPointLabel)
                    .addComponent(yaxisOfEndPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setButton)
                    .addComponent(lineColorButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xaxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisTextFieldActionPerformed

    private void yaxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisTextFieldActionPerformed

    private void lineColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineColorButtonActionPerformed

        color = JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_lineColorButtonActionPerformed

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        int x, y, xEndPoint, yEndPoint;
        String x_str = xaxisTextField.getText();
        String y_str = yaxisTextField.getText();
        String xEndPoint_str = xaxisOfEndPointTextField.getText();
        String yEndPoint_str = yaxisOfEndPointTextField.getText();
        try {
            x = Integer.parseInt(x_str);
            y = Integer.parseInt(y_str);
            xEndPoint = Integer.parseInt(xEndPoint_str);
            yEndPoint = Integer.parseInt(yEndPoint_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
            return;
        }
        if (x < 0 || y < 0 || xEndPoint < 0 || yEndPoint < 0) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
        }
        
        LineSegment l = new LineSegment(new Point(x, y),new Point(xEndPoint, yEndPoint));
        
        l.setColor(color);
        d.addShape(l);
        d.repaint();
        c.addItem("Line " + i_l);
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_setButtonActionPerformed

    private void xaxisOfEndPointTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisOfEndPointTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisOfEndPointTextFieldActionPerformed

    private void yaxisOfEndPointTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisOfEndPointTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisOfEndPointTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LineSegmentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LineSegmentInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endPointLabel;
    private javax.swing.JButton lineColorButton;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton setButton;
    private javax.swing.JLabel xaxisLabel;
    private javax.swing.JTextField xaxisOfEndPointTextField;
    private javax.swing.JLabel xaxisOfEnfPointLabel;
    private javax.swing.JTextField xaxisTextField;
    private javax.swing.JLabel yaxisLabel;
    private javax.swing.JLabel yaxisOfEndPointLabel;
    private javax.swing.JTextField yaxisOfEndPointTextField;
    private javax.swing.JTextField yaxisTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node node) {
        this.parent=node;
    }

    @Override
    public Node getParentNode() {
        return parent;
    }
}
