/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mycompany.lab8.DrawingPanel;
import com.mycompany.lab8.Node;
import com.mycompany.lab8.Oval;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class OvalGui extends javax.swing.JFrame implements Node{
Node parent;
    int noOfCircles;
    private DrawingPanel drawingPanel;
    JComboBox jc = new JComboBox<>();
    Color fillColor, color;

    /**
     * Creates new form CirlceInfo
     */

    public OvalGui(DrawingPanel d, JComboBox jc, int i_c) {
        initComponents();
        this.drawingPanel = d;
        this.jc = jc;
        this.noOfCircles = i_c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        xaxisLabel = new javax.swing.JLabel();
        xaxisTextField = new javax.swing.JTextField();
        yaxisLabel = new javax.swing.JLabel();
        yaxisTextField = new javax.swing.JTextField();
        dimensionsLabel = new javax.swing.JLabel();
        radiusLabel = new javax.swing.JLabel();
        verticalRadiusTextField = new javax.swing.JTextField();
        fillColorButton = new javax.swing.JButton();
        borderColorButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        horizontalRadiusTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Circle");

        positionLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        positionLabel.setText("Postion:");

        xaxisLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisLabel.setText("X:");

        xaxisTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        xaxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisTextFieldActionPerformed(evt);
            }
        });

        yaxisLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisLabel.setText("Y:");

        yaxisTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        yaxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisTextFieldActionPerformed(evt);
            }
        });

        dimensionsLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        dimensionsLabel.setText("Dimensions:");

        radiusLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        radiusLabel.setText("verticalRadius");

        verticalRadiusTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        verticalRadiusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalRadiusTextFieldActionPerformed(evt);
            }
        });

        fillColorButton.setBackground(new java.awt.Color(0, 0, 0));
        fillColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        fillColorButton.setForeground(new java.awt.Color(255, 255, 255));
        fillColorButton.setText("Select Fill Color");
        fillColorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorButtonActionPerformed(evt);
            }
        });

        borderColorButton.setBackground(new java.awt.Color(0, 0, 0));
        borderColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        borderColorButton.setForeground(new java.awt.Color(255, 255, 255));
        borderColorButton.setText("Select Border Color");
        borderColorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorButtonActionPerformed(evt);
            }
        });

        setButton.setBackground(new java.awt.Color(0, 0, 0));
        setButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        setButton.setForeground(new java.awt.Color(255, 255, 255));
        setButton.setText("Create Circle");
        setButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel1.setText("horizalRadius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dimensionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(xaxisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yaxisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radiusLabel)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verticalRadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horizontalRadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borderColorButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionLabel)
                            .addComponent(xaxisLabel))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yaxisLabel)
                            .addComponent(yaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(verticalRadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiusLabel)
                    .addComponent(dimensionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(horizontalRadiusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borderColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xaxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisTextFieldActionPerformed

    private void yaxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisTextFieldActionPerformed

    private void verticalRadiusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalRadiusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verticalRadiusTextFieldActionPerformed

    private void fillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorButtonActionPerformed

        fillColor = JColorChooser.showDialog(null, "Choose color", Color.black);

    }//GEN-LAST:event_fillColorButtonActionPerformed

    private void borderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorButtonActionPerformed

        color = JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_borderColorButtonActionPerformed

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        int x, y, r1,r2;
        String x_str = xaxisTextField.getText();
        String y_str = yaxisTextField.getText();
        String r1_str = verticalRadiusTextField.getText();
        String r2_str= horizontalRadiusTextField.getText();
        try {
            x = Integer.parseInt(x_str);
            y = Integer.parseInt(y_str);
            r1 = Integer.parseInt(r1_str);
            r2 = Integer.parseInt(r2_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
            return;
        }
        if (x < 0 || y < 0 || r1 < 0) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
        }
        Oval c = new Oval(new Point(x, y),r1,r2);
        
        c.setFillColor(fillColor);
        c.setColor(color);
        drawingPanel.addShape(c);
        drawingPanel.repaint();
        jc.addItem("Oval " + noOfCircles);
       this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_setButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CirlceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CirlceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CirlceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CirlceInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CirlceInfo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColorButton;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JButton fillColorButton;
    private javax.swing.JTextField horizontalRadiusTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JLabel radiusLabel;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField verticalRadiusTextField;
    private javax.swing.JLabel xaxisLabel;
    private javax.swing.JTextField xaxisTextField;
    private javax.swing.JLabel yaxisLabel;
    private javax.swing.JTextField yaxisTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node node) {
        this.parent=node;
    }

    @Override
    public Node getParentNode() {
      return parent;
    }
}
