/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mycompany.lab8.DrawingPanel;
import com.mycompany.lab8.Node;
import com.mycompany.lab8.Rectangle;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class RectangleGui extends javax.swing.JFrame implements Node {
Node parent;
    int i_r  ;
    private DrawingPanel drawingPanel;
    JComboBox c = new JComboBox<>();
    Color fillColor, color;

    /**
     * Creates new form RectangleInfo
     */
    public RectangleGui(DrawingPanel d, JComboBox c, int i_r) {
        initComponents();
        this.drawingPanel = d;
        this.c = c;
        this.i_r = i_r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        positionLabel = new javax.swing.JLabel();
        xaxisLabel = new javax.swing.JLabel();
        xaxisTextField = new javax.swing.JTextField();
        yaxisLabel = new javax.swing.JLabel();
        yaxisTextField = new javax.swing.JTextField();
        dimensionsLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        widthLable = new javax.swing.JLabel();
        fillColorButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        borderColorButton = new javax.swing.JButton();
        widthTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Rectangle");

        positionLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        positionLabel.setText("Postion:");

        xaxisLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisLabel.setText("X:");

        xaxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisTextFieldActionPerformed(evt);
            }
        });

        yaxisLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisLabel.setText("Y:");

        yaxisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisTextFieldActionPerformed(evt);
            }
        });

        dimensionsLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        dimensionsLabel.setText("Dimensions:");

        heightLabel.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        heightLabel.setText("Height:");

        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        widthLable.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        widthLable.setText("Width:");

        fillColorButton.setBackground(new java.awt.Color(0, 0, 0));
        fillColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        fillColorButton.setForeground(new java.awt.Color(255, 255, 255));
        fillColorButton.setText("Select Fill Color");
        fillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorButtonActionPerformed(evt);
            }
        });

        setButton.setBackground(new java.awt.Color(0, 0, 0));
        setButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        setButton.setForeground(new java.awt.Color(255, 255, 255));
        setButton.setText("Create Rectangle");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        borderColorButton.setBackground(new java.awt.Color(0, 0, 0));
        borderColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        borderColorButton.setForeground(new java.awt.Color(255, 255, 255));
        borderColorButton.setText("Select Border Color");
        borderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorButtonActionPerformed(evt);
            }
        });

        widthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimensionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(heightLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yaxisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(xaxisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(yaxisTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(xaxisTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(widthLable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(widthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fillColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(borderColorButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(setButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionLabel)
                    .addComponent(xaxisLabel)
                    .addComponent(xaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaxisLabel)
                    .addComponent(yaxisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimensionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(widthLable)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fillColorButton)
                    .addComponent(borderColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xaxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisTextFieldActionPerformed

    private void yaxisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisTextFieldActionPerformed

    private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextFieldActionPerformed

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        int x, y, h, w;
        String x_str = xaxisTextField.getText();
        String y_str = yaxisTextField.getText();
        String w_str = widthTextField.getText();
        String h_str = heightTextField.getText();
        try {
            x = Integer.parseInt(x_str);
            y = Integer.parseInt(y_str);
            w = Integer.parseInt(w_str);
            h = Integer.parseInt(h_str);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
            return;
        }
        if (x < 0 || y < 0 || h < 0 || w < 0) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
        }
        Rectangle r = new Rectangle(new Point(x, y),w,h);
        
        r.setFillColor(fillColor);
        r.setColor(color);
        drawingPanel.addShape(r);
        drawingPanel.repaint();
        c.addItem("Rectangle " + i_r);
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_setButtonActionPerformed

    private void fillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorButtonActionPerformed

        fillColor = JColorChooser.showDialog(null, "Choose color", Color.black);


    }//GEN-LAST:event_fillColorButtonActionPerformed

    private void borderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorButtonActionPerformed
        
        color = JColorChooser.showDialog(null, "Choose color", Color.black);

    }//GEN-LAST:event_borderColorButtonActionPerformed

    private void widthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RectangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RectangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RectangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RectangleInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RectangleInfo(null,null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColorButton;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JButton fillColorButton;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JButton setButton;
    private javax.swing.JLabel widthLable;
    private javax.swing.JTextField widthTextField;
    private javax.swing.JLabel xaxisLabel;
    private javax.swing.JTextField xaxisTextField;
    private javax.swing.JLabel yaxisLabel;
    private javax.swing.JTextField yaxisTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node node) {
       this.parent=node;
    }

    @Override
    public Node getParentNode() {
      return parent;
    }
}
