/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mycompany.lab8.DrawingPanel;
import com.mycompany.lab8.Node;
import com.mycompany.lab8.Triangle;
import java.awt.Color;
import java.awt.Point;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TriangleGui extends javax.swing.JFrame implements Node {
     Node parent;
    int noOfTriangles  ;
    private DrawingPanel drawingPanel;
    JComboBox c = new JComboBox<>();
    Color fillColor, color;
    /**
     * Creates new form TriangleInfo
     */
    
     public TriangleGui(DrawingPanel d, JComboBox c, int i_t) {
        initComponents();
        this.drawingPanel = d;
        this.c = c;
        this.noOfTriangles = i_t;
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fillColorButton = new javax.swing.JButton();
        positionLabelOfPointOne = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        xaxisLabelOfPointOne = new javax.swing.JLabel();
        borderColorButton = new javax.swing.JButton();
        xaxisTextFieldOfPointOne = new javax.swing.JTextField();
        yaxisLabelOfPointOne = new javax.swing.JLabel();
        yaxisTextFieldOfPointOne = new javax.swing.JTextField();
        yaxisTextFieldOfPointTwo = new javax.swing.JTextField();
        positionLabelOfPointTwo = new javax.swing.JLabel();
        xaxisLabelOfPointTwo = new javax.swing.JLabel();
        xaxisTextFieldOfPointTwo = new javax.swing.JTextField();
        yaxisLabelOfPointTwo = new javax.swing.JLabel();
        yaxisTextFieldOfPointThree = new javax.swing.JTextField();
        positionLabelOfPointThree = new javax.swing.JLabel();
        xaxisLabelOfPointThree = new javax.swing.JLabel();
        xaxisTextFieldOfPointThree = new javax.swing.JTextField();
        yaxisLabelOfPointThree = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Triangle");

        fillColorButton.setBackground(new java.awt.Color(0, 0, 0));
        fillColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        fillColorButton.setForeground(new java.awt.Color(255, 255, 255));
        fillColorButton.setText("Select Fill Color");
        fillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillColorButtonActionPerformed(evt);
            }
        });

        positionLabelOfPointOne.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        positionLabelOfPointOne.setText("Postion of first point:");

        setButton.setBackground(new java.awt.Color(0, 0, 0));
        setButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        setButton.setForeground(new java.awt.Color(255, 255, 255));
        setButton.setText("Create Triangle");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        xaxisLabelOfPointOne.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisLabelOfPointOne.setText("X1:");

        borderColorButton.setBackground(new java.awt.Color(0, 0, 0));
        borderColorButton.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        borderColorButton.setForeground(new java.awt.Color(255, 255, 255));
        borderColorButton.setText("Select Border Color");
        borderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borderColorButtonActionPerformed(evt);
            }
        });

        xaxisTextFieldOfPointOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisTextFieldOfPointOneActionPerformed(evt);
            }
        });

        yaxisLabelOfPointOne.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisLabelOfPointOne.setText("Y1:");

        yaxisTextFieldOfPointOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisTextFieldOfPointOneActionPerformed(evt);
            }
        });

        yaxisTextFieldOfPointTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisTextFieldOfPointTwoActionPerformed(evt);
            }
        });

        positionLabelOfPointTwo.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        positionLabelOfPointTwo.setText("Postion of second point:");

        xaxisLabelOfPointTwo.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisLabelOfPointTwo.setText("X2:");

        xaxisTextFieldOfPointTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisTextFieldOfPointTwoActionPerformed(evt);
            }
        });

        yaxisLabelOfPointTwo.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisLabelOfPointTwo.setText("Y2:");

        yaxisTextFieldOfPointThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaxisTextFieldOfPointThreeActionPerformed(evt);
            }
        });

        positionLabelOfPointThree.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        positionLabelOfPointThree.setText("Postion of third point:");

        xaxisLabelOfPointThree.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        xaxisLabelOfPointThree.setText("X3:");

        xaxisTextFieldOfPointThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xaxisTextFieldOfPointThreeActionPerformed(evt);
            }
        });

        yaxisLabelOfPointThree.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        yaxisLabelOfPointThree.setText("Y3:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fillColorButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borderColorButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(positionLabelOfPointThree)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(positionLabelOfPointOne, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(positionLabelOfPointTwo, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xaxisLabelOfPointOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xaxisLabelOfPointTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(xaxisLabelOfPointThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yaxisLabelOfPointOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yaxisLabelOfPointTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yaxisLabelOfPointThree))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(yaxisTextFieldOfPointTwo))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(xaxisTextFieldOfPointTwo)
                                                .addComponent(xaxisTextFieldOfPointOne, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(yaxisTextFieldOfPointOne, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(yaxisTextFieldOfPointThree)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(xaxisTextFieldOfPointThree, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(setButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xaxisTextFieldOfPointOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xaxisLabelOfPointOne)
                    .addComponent(positionLabelOfPointOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yaxisTextFieldOfPointOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yaxisLabelOfPointOne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xaxisTextFieldOfPointTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xaxisLabelOfPointTwo)
                    .addComponent(positionLabelOfPointTwo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yaxisTextFieldOfPointTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yaxisLabelOfPointTwo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xaxisTextFieldOfPointThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xaxisLabelOfPointThree)
                            .addComponent(positionLabelOfPointThree))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yaxisTextFieldOfPointThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(yaxisLabelOfPointThree, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fillColorButton)
                    .addComponent(borderColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(setButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillColorButtonActionPerformed

        fillColor = JColorChooser.showDialog(null, "Choose color", Color.black);

    }//GEN-LAST:event_fillColorButtonActionPerformed

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
        int x1, y1, x2, y2, x3, y3;
        String x1_str = xaxisTextFieldOfPointOne.getText();
        String y1_str = yaxisTextFieldOfPointOne.getText();
        String x2_str = xaxisTextFieldOfPointTwo.getText();
        String y2_str = yaxisTextFieldOfPointTwo.getText();
        String x3_str = xaxisTextFieldOfPointThree.getText();
        String y3_str = yaxisTextFieldOfPointThree.getText();
        try {
            x1 = Integer.parseInt(x1_str);
            y1 = Integer.parseInt(y1_str);
            x2 = Integer.parseInt(x2_str);
            y2 = Integer.parseInt(y2_str);
            x3 = Integer.parseInt(x3_str);
            y3 = Integer.parseInt(y3_str);    
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
            return;
        }
        if (x1 < 0 || y1 < 0 || x2 < 0 || y2 < 0 || x3 < 0 || y3 < 0) {
            JOptionPane.showMessageDialog(null, "Invalid input!!");
        }
        Point p1 = new Point(x1,y1);
        Point p2 = new Point(x2,y2);
        Point p3 = new Point(x3,y3);
        
        Triangle t = new Triangle(p1,p2,p3);
        
        t.setFillColor(fillColor);
        t.setColor(color);
        drawingPanel.addShape(t);
        drawingPanel.repaint();
        c.addItem("Triangle " + noOfTriangles);
        this.setVisible(false);
        ((JFrame)getParentNode()).setVisible(true);
    }//GEN-LAST:event_setButtonActionPerformed

    private void borderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borderColorButtonActionPerformed

        color = JColorChooser.showDialog(null, "Choose color", Color.black);
    }//GEN-LAST:event_borderColorButtonActionPerformed

    private void xaxisTextFieldOfPointOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisTextFieldOfPointOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisTextFieldOfPointOneActionPerformed

    private void yaxisTextFieldOfPointOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisTextFieldOfPointOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisTextFieldOfPointOneActionPerformed

    private void yaxisTextFieldOfPointTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisTextFieldOfPointTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisTextFieldOfPointTwoActionPerformed

    private void xaxisTextFieldOfPointTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisTextFieldOfPointTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisTextFieldOfPointTwoActionPerformed

    private void yaxisTextFieldOfPointThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaxisTextFieldOfPointThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yaxisTextFieldOfPointThreeActionPerformed

    private void xaxisTextFieldOfPointThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xaxisTextFieldOfPointThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xaxisTextFieldOfPointThreeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borderColorButton;
    private javax.swing.JButton fillColorButton;
    private javax.swing.JLabel positionLabelOfPointOne;
    private javax.swing.JLabel positionLabelOfPointThree;
    private javax.swing.JLabel positionLabelOfPointTwo;
    private javax.swing.JButton setButton;
    private javax.swing.JLabel xaxisLabelOfPointOne;
    private javax.swing.JLabel xaxisLabelOfPointThree;
    private javax.swing.JLabel xaxisLabelOfPointTwo;
    private javax.swing.JTextField xaxisTextFieldOfPointOne;
    private javax.swing.JTextField xaxisTextFieldOfPointThree;
    private javax.swing.JTextField xaxisTextFieldOfPointTwo;
    private javax.swing.JLabel yaxisLabelOfPointOne;
    private javax.swing.JLabel yaxisLabelOfPointThree;
    private javax.swing.JLabel yaxisLabelOfPointTwo;
    private javax.swing.JTextField yaxisTextFieldOfPointOne;
    private javax.swing.JTextField yaxisTextFieldOfPointThree;
    private javax.swing.JTextField yaxisTextFieldOfPointTwo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node node) {
       this.parent=node;
    }

    @Override
    public Node getParentNode() {
      return parent;
    }
}
